# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_auto_20170223_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=255)),
                ('project_env_id', models.IntegerField(max_length=11)),
            ],
        ),
    ]
